"""
Generate appendix LaTeX tables from seed_metrics.json (3 training seeds).

Complementary to gen_appendix_bootstrap.py: bootstrap captures test-set
finite-size uncertainty; this captures training (initialization + SGD) variance.
"""
import json, os

ROOT = os.path.join(os.path.dirname(__file__), '..')
SEED = json.load(open(os.path.join(ROOT, 'status/seed_metrics.json')))

TASK_NAME = {
    'T1': r'NS Vort$^\dagger$',
    'T2': 'Torus Adv',
    'T3_T3_ellipsoid_surface_flow': 'Ellips Flow',
    'T5': 'Maxwell',
    'T6': 'Wilson',
    'T7': 'Yang--Mills',
    'T8': r'Airfoil$^\dagger$',
}
TASK_ORDER = ['T1', 'T2', 'T3_T3_ellipsoid_surface_flow', 'T5', 'T6', 'T7', 'T8']

MODEL_NAME = {
    'gcn': 'GCN', 'gat': 'GAT', 'schnet': 'SchNet', 'egnn': 'EGNN',
    'mpsn': 'MPSN', 'sccnn': 'SCCNN',
    'gauge_cnn': 'GaugeEqCNN', 'gem_cnn': 'GEM-CNN',
    'cw_net': 'CW Net', 'clifford_smpn': 'Clifford-SMPN',
    'fno': 'FNO', 'deeponet': 'DeepONet', 'ours': 'Ours',
}
MODEL_ORDER = ['gcn', 'gat', 'schnet', 'egnn', 'mpsn', 'sccnn',
               'gauge_cnn', 'gem_cnn', 'cw_net', 'clifford_smpn',
               'fno', 'deeponet', 'ours']

METRICS = [('SSIM', r'$\uparrow$'), ('Pearson', r'$\uparrow$'), ('NRMSE', r'$\downarrow$')]


def fmt_cell(ms, metric):
    """Std-only (point estimates already in main-text table)."""
    digits = 4 if metric == 'NRMSE' else 3
    s, n = ms['std'], ms.get('n_seeds', 1)
    if n < 2:
        return r'$(n{=}1)$'
    return f"$\\pm\\,{s:.{digits}f}$"


def build_compact_all(metric):
    # Transposed: rows = models, cols = tasks
    lines = [r'\begin{table}[t]', r'\centering\scriptsize',
             rf'\caption{{\textbf{{{metric}}} cross-seed std (3 training seeds: 42, 1, 2; '
             r'point estimates in main-text Table~\ref{tab:main}). '
             r'Std is the unbiased sample std across seeds; this captures '
             r'initialization + SGD variance, complementing the test-set bootstrap of '
             r'Tables~\ref{tab:boot-all-ssim}--\ref{tab:boot-all-nrmse}.}',
             rf'\label{{tab:seed-all-{metric.lower()}}}',
             r'\resizebox{\linewidth}{!}{%',
             r'\begin{tabular}{l' + 'c' * len(TASK_ORDER) + '}',
             r'\toprule',
             'Method & ' + ' & '.join(TASK_NAME[t].replace('&', r'\&') for t in TASK_ORDER) + r' \\',
             r'\midrule']
    for m in MODEL_ORDER:
        row = [MODEL_NAME[m]]
        for t in TASK_ORDER:
            data = SEED.get(t, {})
            if m in data and metric in data[m]:
                row.append(fmt_cell(data[m][metric], metric))
            else:
                row.append('N/A')
        lines.append(' & '.join(row) + r' \\')
    lines.extend([r'\bottomrule', r'\end{tabular}%', r'}', r'\end{table}'])
    return '\n'.join(lines)


def main():
    out_dir = '/home/dzheng/GaugeStructuredHodgeMP_report/paper/Formatting_Instructions_For_NeurIPS_2026EN'
    out_path = os.path.join(out_dir, 'appendix_seed.tex')

    chunks = [r'''% Auto-generated by scripts/gen_appendix_seed.py
% Cross-seed (training) variance over 3 seeds: 42, 1, 2.
% Complementary to appendix_bootstrap.tex (which fixes seed=42 and bootstraps
% over the test set). For each (task, method) we re-trained the model from
% scratch under three independent seeds (42 from the original main-table run,
% 1 and 2 added subsequently) and report the unbiased sample mean and std
% of each test-set metric across the three runs.

\subsection{Cross-seed training variance}
\label{app:seed-variance}

To complement the bootstrap analysis of Section~\ref{app:bootstrap}, which
isolates test-set finite-size uncertainty under a fixed training run, we
also retrained every (task, method) combination under three independent
seeds (42, 1, and 2) and report the resulting cross-seed unbiased
sample standard deviation of each metric in
Tables~\ref{tab:seed-all-ssim}--\ref{tab:seed-all-nrmse}; the point
estimates themselves are given in the main-text Table~\ref{tab:main}
and are not duplicated here. This captures the
\emph{training-time} variance from random initialization and stochastic
gradient noise that the bootstrap cannot see, and addresses the
seed-variance limitation acknowledged in Section~\ref{app:bootstrap}.

We caution that with only $n=3$ seeds the std estimate itself has wide
confidence (the standard error of an unbiased sample std is
$\approx \sigma/\sqrt{2(n-1)} = \sigma/2$ here); the numbers should be
read as an order-of-magnitude bound, not a high-precision interval. On
the tasks where $n$=3 is unavailable for a particular cell (an N/A or
$n{=}1$ marker), the corresponding entry is missing because the seed-1/2
re-runs failed (typically a transient pipeline issue rather than a model
failure); the seed=42 main-table value remains valid.

The bootstrap and seed-variance estimates measure different sources of
uncertainty and can be reported jointly: bootstrap-std bounds how the
metric would change on a different draw of the test set, while
seed-std bounds how it would change on a different draw of training noise.
Method ranking is preserved under both notions of uncertainty.
''']

    for metric, _ in METRICS:
        chunks.append(build_compact_all(metric))
        chunks.append('')

    with open(out_path, 'w') as f:
        f.write('\n\n'.join(chunks))
    print(f'Wrote: {out_path}')


if __name__ == '__main__':
    main()
